version: '3.3'

services:

  web:
    image: nginx:alpine
    volumes:
      - "./src:/var/www"
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
    ports:
      - "8080:80"
      - "3000:443"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app
      - mysql

  app:
    build:
      context: ./src
      dockerfile: /${PWD}/Dockerfile
    restart: always
    user: root
    volumes:
      - "./src:/var/www"
      # - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: always
    tty: true
    networks:
      - app-network
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

networks:
  app-network:
     driver: bridge

volumes:
  mysql-data:
     driver: local
